#pragma once

namespace uti
{
	enum keycodes
	{
		keycode_lbutton		= 0x01, //left mouse button
		keycode_rbutton		= 0x02, //right mouse button
		keycode_cancel		= 0x03, //control - break processing
		keycode_mbutton		= 0x04, //middle mouse button(three - button mouse)
		keycode_xbutton1	= 0x05, //x1 mouse button
		keycode_xbutton2	= 0x06, //x2 mouse button
		keycode_back		= 0x08,	//backspace key
		keycode_tab			= 0x09,	//tab key
		keycode_clear		= 0x0c, //clear key
		keycode_return		= 0x0d, //enter key
		keycode_shift		= 0x10, //shift key
		keycode_control		= 0x11, //ctrl key
		keycode_menu		= 0x12, //alt key
		keycode_pause		= 0x13, //pause key
		keycode_capital		= 0x14, //caps lock key
		keycode_kana		= 0x15,	//ime kana mode
		keycode_hanguel		= 0x15, //ime hanguel mode(maintained for compatibility; use vk_hangul)
		keycode_hangul		= 0x15, //ime hangul mode
		keycode_junja		= 0x17, //ime junja mode
		keycode_final		= 0x18, //ime final mode
		keycode_hanja		= 0x19, //ime hanja mode
		keycode_kanji		= 0x19, //ime kanji mode
		keycode_escape		= 0x1b, //esc key
		keycode_convert		= 0x1c, //ime convert
		keycode_nonconvert	= 0x1d, //ime nonconvert
		keycode_accept		= 0x1e, //ime accept
		keycode_modechange	= 0x1f, //ime mode change request
		keycode_space		= 0x20, //spacebar
		keycode_prior		= 0x21, //page up key
		keycode_next		= 0x22, //page down key
		keycode_end			= 0x23, //end key
		keycode_home		= 0x24, //home key
		keycode_left		= 0x25, //left arrow key
		keycode_up			= 0x26, //up arrow key
		keycode_right		= 0x27, //right arrow key
		keycode_down		= 0x28, //down arrow key
		keycode_select		= 0x29, //select key
		keycode_print		= 0x2a, //print key
		keycode_execute		= 0x2b, //execute key
		keycode_snapshot	= 0x2c, //print screen key
		keycode_insert		= 0x2d, //ins key
		keycode_delete		= 0x2e, //del key
		keycode_help		= 0x2f, //help key

		keycode_0 = 0x30,	//0 key
		keycode_1 = 0x31,	//1 key
		keycode_2 = 0x32,	//2 key
		keycode_3 = 0x33,	//3 key
		keycode_4 = 0x34,	//4 key
		keycode_5 = 0x35,	//5 key
		keycode_6 = 0x36,	//6 key
		keycode_7 = 0x37,	//7 key
		keycode_8 = 0x38,	//8 key
		keycode_9 = 0x39,	//9 key
		keycode_a = 0x41,	//a key
		keycode_b = 0x42,	//b key
		keycode_c = 0x43,	//c key
		keycode_d = 0x44,	//d key
		keycode_e = 0x45,	//e key
		keycode_f = 0x46,	//f key
		keycode_g = 0x47,	//g key
		keycode_h = 0x48,	//h key
		keycode_i = 0x49,	//i key
		keycode_j = 0x4a,	//j key
		keycode_k = 0x4b,	//k key
		keycode_l = 0x4c,	//l key
		keycode_m = 0x4d,	//m key
		keycode_n = 0x4e,	//n key
		keycode_o = 0x4f,	//o key
		keycode_p = 0x50,	//p key
		keycode_q = 0x51,	//q key
		keycode_r = 0x52,	//r key
		keycode_s = 0x53,	//s key
		keycode_t = 0x54,	//t key
		keycode_u = 0x55,	//u key
		keycode_v = 0x56,	//v key
		keycode_w = 0x57,	//w key
		keycode_x = 0x58,	//x key
		keycode_y = 0x59,	//y key
		keycode_z = 0x5a,	//z key

		keycode_lwin		= 0x5b, //left windows key(natural keyboard)
		keycode_rwin		= 0x5c, //right windows key(natural keyboard)
		keycode_apps		= 0x5d, //applications key(natural keyboard)
		keycode_sleep		= 0x5f, //computer sleep key
		keycode_numpad0		= 0x60, //numeric keypad 0 key
		keycode_numpad1		= 0x61, //numeric keypad 1 key
		keycode_numpad2		= 0x62, //numeric keypad 2 key
		keycode_numpad3		= 0x63, //numeric keypad 3 key
		keycode_numpad4		= 0x64, //numeric keypad 4 key
		keycode_numpad5		= 0x65, //numeric keypad 5 key
		keycode_numpad6		= 0x66, //numeric keypad 6 key
		keycode_numpad7		= 0x67, //numeric keypad 7 key
		keycode_numpad8		= 0x68, //numeric keypad 8 key
		keycode_numpad9		= 0x69, //numeric keypad 9 key
		keycode_multiply	= 0x6a, //multiply key
		keycode_add			= 0x6b, //add key
		keycode_separator	= 0x6c, //separator key
		keycode_subtract	= 0x6d, //subtract key
		keycode_decimal		= 0x6e, //decimal key
		keycode_divide		= 0x6f, //divide key

		keycode_f1	= 0x70, //f1 key
		keycode_f2	= 0x71, //f2 key
		keycode_f3	= 0x72, //f3 key
		keycode_f4	= 0x73, //f4 key
		keycode_f5	= 0x74, //f5 key
		keycode_f6	= 0x75, //f6 key
		keycode_f7	= 0x76, //f7 key
		keycode_f8	= 0x77, //f8 key
		keycode_f9	= 0x78, //f9 key
		keycode_f10	= 0x79, //f10 key
		keycode_f11	= 0x7a, //f11 key
		keycode_f12	= 0x7b, //f12 key
		keycode_f13	= 0x7c, //f13 key
		keycode_f14	= 0x7d, //f14 key
		keycode_f15	= 0x7e, //f15 key
		keycode_f16	= 0x7f, //f16 key
		keycode_f17	= 0x80, //f17 key
		keycode_f18	= 0x81, //f18 key
		keycode_f19	= 0x82, //f19 key
		keycode_f20	= 0x83, //f20 key
		keycode_f21	= 0x84, //f21 key
		keycode_f22	= 0x85, //f22 key
		keycode_f23	= 0x86, //f23 key
		keycode_f24	= 0x87, //f24 key

		keycode_numlock				= 0x90, //num lock key
		keycode_scroll				= 0x91, //scroll lock key
		keycode_lshift				= 0xa0, //left shift key
		keycode_rshift				= 0xa1, //right shift key
		keycode_lcontrol			= 0xa2, //left control key
		keycode_rcontrol			= 0xa3, //right control key
		keycode_lmenu				= 0xa4, //left menu key
		keycode_rmenu				= 0xa5, //right menu key
		keycode_browser_back		= 0xa6, //browser back key
		keycode_browser_forward		= 0xa7, //browser forward key
		keycode_browser_refresh		= 0xa8, //browser refresh key
		keycode_browser_stop		= 0xa9, //browser stop key
		keycode_browser_search		= 0xaa, //browser search key
		keycode_browser_favorites	= 0xab, //browser favorites key
		keycode_browser_home		= 0xac, //browser start and home key
		keycode_volume_mute			= 0xad, //volume mute key
		keycode_volume_down			= 0xae, //volume down key
		keycode_volume_up			= 0xaf, //volume up key
		keycode_media_next_track	= 0xb0, //next track key
		keycode_media_prev_track	= 0xb1, //previous track key
		keycode_media_stop			= 0xb2, //stop media key
		keycode_media_play_pause	= 0xb3, //play / pause media key
		keycode_launch_mail			= 0xb4, //start mail key
		keycode_launch_media_select	= 0xb5, //select media key
		keycode_launch_app1			= 0xb6, //start application 1 key
		keycode_launch_app2			= 0xb7, //start application 2 key

		keycode_oem_1		= 0xba, //used for miscellaneous characters; it can vary by keyboard. for the us standard keyboard, the ';:' key
		keycode_oem_plus	= 0xbb, //for any country / region, the '+' key
		keycode_oem_comma	= 0xbc, //for any country / region, the ',' key
		keycode_oem_minus	= 0xbd, //for any country / region, the '-' key
		keycode_oem_period	= 0xbe, //for any country / region, the '.' key
		keycode_oem_2		= 0xbf, //used for miscellaneous characters; it can vary by keyboard. for the us standard keyboard, the '/?' key
		keycode_oem_3		= 0xc0, //used for miscellaneous characters; it can vary by keyboard.	for the us standard keyboard, the '`~' key
		keycode_oem_4		= 0xdb, //used for miscellaneous characters; it can vary by keyboard.	for the us standard keyboard, the '[{' key
		keycode_oem_5		= 0xdc, //used for miscellaneous characters; it can vary by keyboard.	for the us standard keyboard, the '\|' key
		keycode_oem_6		= 0xdd, //used for miscellaneous characters; it can vary by keyboard.	for the us standard keyboard, the ']}' key
		keycode_oem_7		= 0xde, //used for miscellaneous characters; it can vary by keyboard.	for the us standard keyboard, the 'single-quote/double-quote' key
		keycode_oem_8		= 0xdf, //used for miscellaneous characters; it can vary by keyboard.
		keycode_oem_102		= 0xe2, //either the angle bracket key or the backslash key on the rt 102 - key keyboard
		keycode_processkey	= 0xe5, //ime process key
		keycode_packet		= 0xe7,	//used to pass unicode characters as if they were keystrokes.the vk_packet key is the low word of a 32 - bit virtual key value used for non - keyboard input methods.for more information, see remark in keybdinput, sendinput, wm_keydown, and wm_keyup
		keycode_attn		= 0xf6, //attn key
		keycode_crsel		= 0xf7, //crsel key
		keycode_exsel		= 0xf8, //exsel key
		keycode_ereof		= 0xf9, //erase eof key
		keycode_play		= 0xfa, //play key
		keycode_zoom		= 0xfb, //zoom key
		keycode_noname		= 0xfc, //reserved
		keycode_pa1			= 0xfd, //pa1 key
		keycode_oem_clear	= 0xfe, //clear key
	};
}
